### ISSUE TITLE
Redirect problem

### ISSUE THREAD

**Issue by Cybernetint** [emspay/ems-online-prestashop-1.7#7]
Hello, we have problem with the EMS PRESTASHOP plugin version 1.3.0. in TEST mode.
We are using prestashop version 1.7.6.7. 
After encoding sandbox card numbers (for exemple visa) there is a redirect URL to : https://api.online.emspay.eu/redirect/78df8ac8-f3df-4370-9e9e-9a142e5a3b4b/to/payment/ but nothing happen and the page stay blank-empty.  Are you experimented a same issue?

**Comment by tiutiunnykleasoft** [comment]
@Cybernetint 
Yes, we are seeing the same problem, I will create a ticket to solve this problem.
Could you please clarify if you are using the same plugin in production?

**Comment by Cybernetint** [comment]
Yes TEST and PROD will use the same version 1.3.0. of the plugin

**Comment by tiutiunnykleasoft** [comment]
@Cybernetint , Ok, Please specify which payment method you are using for the test transaction?

**Comment by Cybernetint** [comment]
Visa with sandbox : VISA #2	4035 8740 0042 4977	12/2025	123	n/a

**Comment by Cybernetint** [comment]
into https://portal.emspay.eu/ the payment status is "pending" blocked on "started_3d_secure_transaction"

**Comment by tiutiunnykleasoft** [comment]
@Cybernetint , so if you can view a transaction status, can you share an order_id then?

**Comment by Cybernetint** [comment]
Carte
**** 403587******4977
Type
Visa
ID de commande
644919e8-8582-4b87-bc9a-2c9e72214ead
Token ID
41193e41-012f-404c-b8d5-340899b5ed20
Montant non saisi
EUR 0,00
Montant saisi
EUR 0,00
Annuler le montant
EUR 0,00

**Comment by tiutiunnykleasoft** [comment]
@Cybernetint 
Don't worry, I already found what I was looking for.
I wanted to receive a payment method such as Credit Card or Klarna Pay Later. As far as I can see, you used a "credit card". This is true?

**Comment by Cybernetint** [comment]
yes i've used VISA pyment method. we want only use: credit cards (mastercard-visa-maestro-vpay), bancontact, paypal, payconiq. (the others are desactived into prestashop backoffice)

**Comment by tiutiunnykleasoft** [comment]
@Cybernetint , 

Thanks for your clarification.
As I can see order created successfully, but on stage 3d security verification by Visa, payment progress is blocked and the order is settled expired after 30 min waiting.
so at this point, we have all the required data for the bug-ticket.

**Comment by tiutiunnykleasoft** [comment]
@Cybernetint , did you entered a valid CVC code while payment?

**Comment by Cybernetint** [comment]
yes the code visa is "123"
 VISA #2 : 4035 8740 0042 4977
DATE: 12/2025
CVC : 123

**Comment by Cybernetint** [comment]
Hello have you some news? redirect still not working with the 2 visa SANDBOX TEST cards: 
VISA #1	4012 0010 3714 1112	06/2025	123	test123 > redirect to https://3ds-acs.test.modirum.com/mdpayacs/pareq;mdsessionid=17B1AA3CD9C16A3FFDF358776E640551 >ERROR 500 but payment and order appear ok in backend. 
VISA #2	4035 8740 0042 4977	12/2025	123	n/a > redirect to https://3ds-acs.test.modirum.com/mdpayacs/creq > blank page and nothing happen... (payment and order NOT ok) 
Can you help please? (we are using prestashop 1.7.6.7) 
Thanks

**Comment by aleksandrkhruslovleasoft** [comment]
Hello @Cybernetint. 

We are working on your issue. We will try to complete it asap. We will give you know when the issue will be resolved and the new release will be done.

Best regards,
Alex

**Comment by Cybernetint** [comment]
server error log for visa1 test :

PHP Fatal error:  Uncaught Error: Class 'Model\\Emspay\\EmspayGateway' not found in /home/websites/shop.cbeventsracing.com/modules/emspay/Lib/EmsPayPaymentModule.php:142\nStack trace:\n#0 /home/websites/shop.cbeventsracing.com/modules/emspaycreditcard/emspaycreditcard.php(140): Lib\\EmsPayPaymentModule->getOrderFromDB('68')\n#1 /home/websites/shop.cbeventsracing.com/classes/Hook.php(970): emspayCreditcard->hookPaymentReturn(Array)\n#2 /home/websites/shop.cbeventsracing.com/classes/Hook.php(359): HookCore::coreCallHook(Object(emspayCreditcard), 'hookpaymentRetu...', Array)\n#3 /home/websites/shop.cbeventsracing.com/classes/Hook.php(907): HookCore::callHookOn(Object(emspayCreditcard), 'displayPaymentR...', Array)\n#4 /home/websites/shop.cbeventsracing.com/controllers/front/OrderConfirmationController.php(118): HookCore::exec('displayPaymentR...', Array, 107)\n#5 /home/websites/shop.cbeventsracing.com/controllers/front/OrderConfirmationController.php(97): OrderConfirmationControllerCore->displayPaymentReturn(Object(Order))\n#6 /home/website in /home/websites/shop.cbeventsracing.com/modules/emspay/Lib/EmsPayPaymentModule.php on line 142

**Comment by aleksandrkhruslovleasoft** [comment]
Hi @Cybernetint.

Thank you for your patience. We resolved the issue and include the solution to the new plugin release. You are able to download the new plugin version [here](https://github.com/emspay/ems-online-prestashop-1.7/releases/tag/1.3.1)

Give us know if you'll need something else.

Best regards,
Alex.

**Comment by Cybernetint** [comment]
Hello, 

Good job! all is going well with this version ! Thanks you!

Best regards,

Cybernet
